backend:
  image: gitlab.praktikum-services.ru:5050/anton-borodinskiy/sausage-store/sausage-backend
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

imagePullSecrets: 
  name: docker-config-secret

autoscaling:
  vpa:
    enabled: false
    updateMode: "Auto"
    controlledResources: ["cpu", "memory"]
    minAllowed:
      cpu: 100m
      memory: 128Mi
    maxAllowed:
      cpu: 500m
      memory: 2048Mi