---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  ingressClassName: "nginx"
  tls:
    - secretName: ingress-example-tls
    - hosts:
        - {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "frontend.fullname" . }}
              port:
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.backend.host }}
              port:
                number: {{ .Values.backend.port }}
