      - name: copy_front_service
        become: true
        template:
           src: sausage-store-frontend.service.j2
           dest: /etc/systemd/system/sausage-store-frontend.service
        listen: "restart front"
      
      - name: Reload daemon
        become: true
        systemd: 
           daemon_reload: yes
        listen: "restart front"

      - name: Start Frontend
        become: true
        service: name=sausage-store-frontend.service state=restarted enabled=yes
        listen: "restart front"


