apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-report.fullname" . }}
  labels:
    {{- include "backend-report.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "backend-report.selectorLabels" . | nindent 4 }}
