- hosts: all
  tasks:
      - name: Update and upgrade apt packages
        become: true
        apt:
         update_cache: yes

- hosts: all
  roles:
    - { role: frontend }

- hosts: all
  roles:
    - { role: backend }
